### ISSUE TITLE
Feature Request: 'Remote' Lyrics

### ISSUE THREAD

**Issue by InCaseItWorks** [Jugran/lyrics-in-terminal#10]
Hello

First of all, thanks for the script. It's brilliant. It adds what I've really been missing from Spotify.

This is not issue, more a freature request: **Is it possible at all to add support for Spotify's remote play feature?**

For example, I use a Raspberry Pi with spotifyd, which I can control via the Spotify linux client, but also in a shell using 'spt' (spotify-tui). It would be very nice to have everything in the shell in two tabs, the player controls in one as well as the lyrics in another.

Right now, I cannot find a way to tell the 'lyrics' command to use a running spotify instance on another device.

Thank you, and again, great work!
Chris

**Comment by Jugran** [comment]
Hi
Glad to hear you like this simple solo project of mine :)

Unfortunately spotify-tui does not provide a MPRIS interface, which is required by lyrics command to read metadata of currently playing media.

[SpotPRIS2](https://github.com/freundTech/SpotPRIS2) project aims to provide a MPRIS interface for Spotify Remote Connect devices, and should help you with your use case (I have not tested this but looks promising).
You can also track future developments of MPRIS feature implementation in spotify-tui from this [issue](https://github.com/Rigellute/spotify-tui/issues/147).

**Comment by InCaseItWorks** [comment]
Thanks a lot for your answers. I'll definitely check it out!
