### ISSUE TITLE
button/keystroke to recheck lyrics and select the next one if they are wrong?

### ISSUE THREAD

**Issue by Konpaku-LVX** [Jugran/lyrics-in-terminal#12]
![image](https://user-images.githubusercontent.com/76745649/117593819-bcc8d600-b10a-11eb-9bbd-ab7d212bce87.png)

part 3 is playing but its displaying the lyrics to part 1, i think it would be nice to remedy this issue somehow, as it seems like it could be a common occurrence

**Comment by Jugran** [comment]
I was actually thinking of implementing something similar for a future release, but for now, you can manually edit the lyrics for such songs by opening them on the editor (keybinding <kbd>e</kbd>) and replacing them with correct lyrics. 

You can also try switching sources and check if it fetches correct lyrics, (<kbd>R</kbd> for azlyrics, <kbd>r</kbd> for google)
