### ISSUE TITLE
mpv player is not running

### ISSUE THREAD

**Issue by frojnd** [Jugran/lyrics-in-terminal#13]
First of all thank you for this awesome project :) 

I am mainly using mpsyt for my music needs: https://github.com/mps-youtube/mps-youtube And I noticed that many times I don't get lyrics when playing songs with mpsyt. 9/10 it won't w ork. I'll get mpv player is not running message.

mpv is running though since I have it set as default player with mpsyt:

ps aux | grep mpv:
```
frojnd     62995  9.3  1.0 1651740 84340 pts/5   Sl+  10:27   0:00 mpv --force-media-title="I Surrender - Hillsong Worship" --no-ytdl --really-quiet --volume=100 https://r6---sn-nv47lnls.googlevideo.com/videoplayback?expire=1620656556&ei=TO2YYL-TIsLW-gax3o24BA&ip=2a00%3Aee2%3A1608%3A605%3Ae2a%3Aa65f%3A79e2%3Ae7f0&id=o-ABueUvjHI-yhwdoThp0C9QiK3HFN8xmhe7TOmKX1zA3q&itag=251&source=youtube&requiressl=yes&mh=ia&mm=31%2C26&mn=sn-nv47lnls%2Csn-hpa7kn7l&ms=au%2Conr&mv=m&mvi=6&pl=55&initcwndbps=1250000&vprv=1&mime=audio%2Fwebm&ns=M6schCKQ9ZaPjqnKKhYbrI4F&gir=yes&clen=11046589&dur=675.281&lmt=1603665610179208&mt=1620634862&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5511222&n=d0SJKKe0CDwpgxs4inH&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJWF1A0oMKVI7_lUJw8ZN0EwAAhQV3VSTdAoUtQnhWmCAiEAnpTO6lSKhCbhu7Try7Pn5QqvfjDGFaJQ4SFjWp06b6o%3D&sig=AOq0QJ8wRQIhALKs97yQWlVVycIJ46NPtTJpeZPUocqW2t-FhSQONfePAiBhlqjKpu88rlK-cNibwPdzGTKPbyQ20R-QxZL93EfeOw== --input-conf=/tmp/mpsyt-inputjvm_iysy --input-unix-socket=/tmp/mpsyt-mpvej9vqa8p.sock
```

Please note that I have mpv-mpris installed and if I am running mpv *.flac it recognizes mpv each time. But when running it from mpsyt 9/10 times it won't recognize it as running app?

**Comment by nisiddharth** [comment]
I am getting the same problem. Basically if playing YouTube videos in MPV, lyrics shows "mpv player is not running." Works with mp3, MPRIS is working properly.

**Comment by nisiddharth** [comment]
Okay, so files downloaded from YT also don't work due to a lack of appropriate tags. Understood. This will happen with all players.

**Comment by nisiddharth** [comment]
Hi @Jugran, I've created PR #20, please consider reviewing it.

**Comment by Jugran** [comment]
Pull request #20 by @nisiddharth has been merged with the main branch and this issue should be fixed in the next release. 

Till then you can install the package from the main branch. To do that, follow the instructions from the wiki under the section [Installing from the source](https://github.com/Jugran/lyrics-in-terminal/wiki/Installation#from-source).

**Comment by akash-258** [comment]
This issue still persists
