### ISSUE TITLE
Add autoscrolling functionality & issues with songs that have no lyrics.

### ISSUE THREAD

**Issue by Doofitator** [Jugran/lyrics-in-terminal#17]
Back when Google Play Music was a thing, I used a desktop client called [Google Play Music Desktop Player](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-), and it had a feature I've never been able to replicate since: lyrics that autoscroll. It wasn't perfectly in time, and I don't expect it to be, but it was handy that nine times out of ten you didn't have to interact with the player to be able to see the current lyrics.
Is this a feature you think could be implemented into your program?

Additionally, I've noticed that when the shuffle lands on a song that has no lyrics, we get mixed results. Sometimes the player says it can't connect to the internet, and other times (as pictured) it picks up the lyrics from a different song with a similar title.
![image](https://user-images.githubusercontent.com/4780013/134441817-fbf32bad-057f-498f-ac13-dd434ae6f805.png)

Please note that this isn't to say I don't really appreciate your software - it is by far the nearest thing out there to what I'm after, and has clearly been built to a high standard.

**Comment by Jugran** [comment]
This issue is being tracked in #29
