### ISSUE TITLE
 is there a way to change the editor that is used when pressing e? 

### ISSUE THREAD

**Issue by Konpaku-LVX** [Jugran/lyrics-in-terminal#18]
it seems to use nano by default, but i prefer using mousepad, is there a way to change it?

**Comment by Jugran** [comment]
It uses the default editor set by your shell (usually nano by default).

To change your editor, add `export EDITOR=editor name` in your .bashrc file.

**Comment by Konpaku-LVX** [comment]
Nice thanks :D
