### ISSUE TITLE
Error editing lyrics after updating to Python 3.10

### ISSUE THREAD

**Issue by YesterKo** [Jugran/lyrics-in-terminal#19]
#### Steps to reproduce the issue

1. Spotify playing with song   `Ma Ei Oska Kaine Peaga Peol Midagi Teha`
2. press `e`
3. Error: `Unexpected exception occurred. <class 'FileNotFoundError'>`

System info: Arch Linux, Python 3.10

**Most likely related to Python 3.10, before updating it worked flawlessly**

**Comment by sarthak1337** [comment]
Are you sure you have nano installed? I also have only vim installed and had the same issue. I am also running Arch Linux with Python 3.10.1

**Comment by Jugran** [comment]
Hey @YesterKo, make sure you have either nano installed or have `$EDITOR` environment variable set to the text editor you like to use like vim.

If `$EDITOR` is not set then it tries to open nano by default.
