### ISSUE TITLE
pip install failed on MacOS

### ISSUE THREAD

**Issue by aryantps** [Jugran/lyrics-in-terminal#21]
`pip install lyrics-in-terminal` failed when I tries to install on my mac terminal ( oh my zsh ).

python-version - 3.7
pip version - 22.0.4

Screenshot attached : 

<img width="1440" alt="error-1" src="https://user-images.githubusercontent.com/46716746/157496436-dd594d1d-a685-4b75-bce5-8bb207fb2f8a.png">
<img width="1440" alt="error-2" src="https://user-images.githubusercontent.com/46716746/157496453-c75c234c-bd94-4c81-9663-9f09192342e8.png">

**Comment by Jugran** [comment]
Currently this application is designed to work only on linux platform. 
I do not intent to add support for other operating systems for now, however, I am open to accept contribution for the same.

**Comment by math-gout** [comment]
You can get it to install by running ```brew install dbus``` first, although it is quite useless since no player is detected.
