### ISSUE TITLE
Unexpected exception occurred

### ISSUE THREAD

**Issue by mrsteve0924** [Jugran/lyrics-in-terminal#24]
recently upgraded to version 1.4.4-1 and now getting this error

Unexpected exception occurred. (<class 'KeyError'>, KeyError('mpd_host'), <traceback object at 0x7fd871257f40>)

downgraded to 1.4.2-1 as a workaround

**Comment by Jugran** [comment]
Seems like your config file did not upgrade properly and have certain entries missing.
Can you provide contents of your `lyrics.cfg` file, it is located under `~/.config/lyrics-in-terminal/lyrics.cfg`

**Comment by mrsteve0924** [comment]
yes that was it. i'm usually logged in as the root user. updating changed the config file in the user account but not the root account.  i just coped the updated config file to the root account and now it works. 

thanks for the help
