### ISSUE TITLE
initial support for termux in android?

### ISSUE THREAD

**Issue by commit-ezza** [Jugran/lyrics-in-terminal#25]
both installation method (pip, source) didn't work. since termux and android is technically still linux, does this will still work? and about the music player, maybe user could use cmus or ncmpcpp, since android apps is containerized and reading music player would require notification access.

**Comment by M1ndo** [comment]
Termux is in isolated environment it cannot access apps outside of termux itself, thus it won't work.
However it do some testing and i'll get back to this issue.
