### ISSUE TITLE
Local mp3 embedded lyrics

### ISSUE THREAD

**Issue by melecoaze** [Jugran/lyrics-in-terminal#30]
Is there any way to make this program show the lyrics that are embedded to the mp3 files?

Would be useful for the songs that can't be found on google or azlyrics

**Comment by Jugran** [comment]
Currently there is no way to read the source file directly. This program works by read metadata supplied by the mpris player.

Support for embedded lyrics varies from player to player, hence won't be implementing that. 
If a particular song's lyrics is missing you can add it manually by pressing edit keybind (default <kbd>e</kbd>)
