### ISSUE TITLE
use youtube music as the main source

### ISSUE THREAD

**Issue by darkralts** [Jugran/lyrics-in-terminal#31]
more often than not, i find myself searching up the song im listening to to copy the lyrics because the other sources either dont have it, or they are wrong,

the lyrics seem to be in plain text and easy to copy, and it uses a bunch of sources, so its like a mega source almost. idk if you still even make this program, but it seems the lyrics source may need an upgrade as i remember it usually working most of the time but now its the other way around, thank you :)

**Comment by Jugran** [comment]
Since adding genius as a fallback source _(v1.7)_, majority of lyrics are being found.

So, I'm closing this issue for now as I no longer see any merit in adding youtube music source.
