### ISSUE TITLE
is there a way to use less with autoswitch on?

### ISSUE THREAD

**Issue by Moanrisy** [Jugran/lyrics-in-terminal#33]
$ lyrics -t Tool Sober | less

less only work for single song.

it can't detect next song

this not working good
$ lyrics | less 

![2023-11-24T19:49:05,032823240+07:00](https://github.com/Jugran/lyrics-in-terminal/assets/17421945/d2d82da7-bf68-467d-9a08-1d717a09e473)

**Comment by Moanrisy** [comment]
Actually I need a way to search or jump at word.

I have 3 format in a lyric (romaji, japanese, translation)

with less, I can jump onto japanese or translation with /
instead of scrolling manually

**Comment by Jugran** [comment]
Changing lyrics text once it is piped to less is not possible.
