### ISSUE TITLE
Genius lyrics source

### ISSUE THREAD

**Issue by 88572** [Jugran/lyrics-in-terminal#37]
AZLyrics does not have lyrics for some songs, so for those it might be a good idea to fetch them from Genius. They have a [public API](https://docs.genius.com/#songs-h2), but I'm not sure this could help.

**Comment by Jugran** [comment]
Genius source is already in works in [feature/genius-lyrics-source](https://github.com/Jugran/lyrics-in-terminal/tree/feature/genius-lyrics-source).

I am looking to release this feature in v1.6.0. Feel free to install from source till then.
