### ISSUE TITLE
writing/author credits?

### ISSUE THREAD

**Issue by iconoclasthero** [Jugran/lyrics-in-terminal#38]
In all honesty, this is probably as important to me as they lyrics in terms of "...hey, this Buddy Miles [~Jimi Hendrix Experience~ Band of Gypsies] cover of 'Down by the River (I Shot My Baby)' is [pretty good](https://en.wikipedia.org/wiki/Down_by_the_River_(Neil_Young_song)#:~:text=A%20cover%20by%20Buddy%20Miles%20charted%20seven%20weeks%20on%20the%20Billboard%20Hot%20100%20from%207/18%20to%208/29/1970%2C%20peaking%20at%20position%2068.)... Is it really a Neil Young song or did someone else write it, like maybe Hendrix?  Also, do I have any covers by Hendrix?"

I don't suppose asscap has an api or is easily parsed, but maybe there's another source for such things?

**Comment by Jugran** [comment]
Please check with latest version v1.7 and cycling through all the sources using <kbd>c</kbd> wheather you get the correct lyrics.

With v1.7 I've added new genius lyrics source as well as cycle lyrics source functionality.


Closing this issue for now.
