### ISSUE TITLE
Support cmus

### ISSUE THREAD

**Issue by nickclyde** [Jugran/lyrics-in-terminal#4]
Hey @Jugran! Love using this with spotify, I prefer it to `clyrics`. Any chance you can add support for the [cmus](https://github.com/cmus/cmus) player? It supports mpris, but I wasn't able to get it to work.

Thanks again for sharing your work!

**Comment by Jugran** [comment]
Can you provide more details about your linux distro and cmus config file.
Did you install from your distro's repository or compiled it yourself?

Because I have tested it with cmus on Fedora workstation 32 and Archlinux, and it works fine.

**Comment by nickclyde** [comment]
:facepalm: 

It turns out that I just hadn't updated your script in a while. Updated to the latest version, it works with cmus now. Sorry to be a bother, and thanks again for your hard work!
