### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by NischalDawadi** [Jugran/lyrics-in-terminal#42]
Unexpected exception occurred. (<class 'KeyError'>, KeyError('find'), <traceback object at 0x7f68a5962840>) 'find'

**Comment by samanshirdell** [comment]
The error message you are seeing, KeyError('find'), indicates that your code is trying to access a key named 'find' in a dictionary or some kind of mapping, but that key does not exist. In Python, a KeyError occurs when you try to access a dictionary with a key that isn't present.

**Comment by NischalDawadi** [comment]
So how can i solve it.

**Comment by samanshirdell** [comment]
Check if the Key Exists in the Dictionary:
Before accessing a key in a dictionary, you can check if it exists using the in keyword.

my_dict = {'example_key': 'example_value'}

if 'find' in my_dict:
    value = my_dict['find']
else:
    print("Key 'find' does not exist in the dictionary.")


Use the get Method:
value = my_dict.get('find', 'default_value')

**Comment by Jugran** [comment]
Seems like search config is not present. Try reinstalling the package through pip.

**Comment by necromeo** [comment]
The issue is there were some config changes added to the latest (1.6.0) version. You can see the details in this [PR](https://github.com/Jugran/lyrics-in-terminal/pull/41/files).
Long story short, add the following fields to your `lyrics.cfg`

```
statusbar=on
# the following must be below the [BINDINGS] header
find=/
find-next=n
find-prev=p
```
Hope this helps.
