### ISSUE TITLE
lyrics crashes from 1.6 onwards when playing with firefox or yewtube

### ISSUE THREAD

**Issue by frojnd** [Jugran/lyrics-in-terminal#48]
When playing music with firefox (youtube) or yewtube: https://github.com/mps-youtube/yewtube lyrics crashes:

Crash line for 1.6 version:
`Unexpected exception occurred. (<class 'KeyError'>, KeyError('find'), <traceback object at 0x7f947b444340>) 'find'`

Crash line for 1.7 version:
`Unexpected exception occurred. (<class 'KeyError'>, KeyError('cycle-source'), <traceback object at 0x7f7a638bbcc0>) 'cycle-source'`

Note that 1.5 version does not crashes:

How I built the package on Alpine linux:
```
depends="python3>=3.6 py3-dbus ncurses"
makedepends="py3-setuptools"

build() {
 	python setup.py build
}

package() {
	python setup.py install \
	-O1 \
	--root="$pkgdir" \
	--skip-build

	install -Dm644 LICENSE \
	-t "$pkgdir/usr/share/licenses/$pkgname"
}
```
Maybe something changed in versions 1.6 and 1.7 that needs to be added (package wise on Alpine linux) ?

**Comment by Jugran** [comment]
Looks like find feature related is missing. Reinstall should fix it.

```sh
pip install --upgrade --force-reinstall lyrics-in-terminal
```


If this still doesn't fix it, then manually add following missing config at location `~/.config/lyrics-in-terminal/lyrics.cfg`
```
find=/
find-next=n
find-prev=p
```
